apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-app-kustomize
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: Team B — deploys the demo app from the demo-app-kustomize repo using Kustomize overlays per env.
  sourceRepos:
    - https://github.com/recmanj/argocd-multirepo-demo-app-kustomize.git
  destinations:
    - namespace: demo-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: apps
      kind: Deployment
    - group: apps
      kind: ReplicaSet
    - group: ""
      kind: Pod
    - group: networking.k8s.io
      kind: Ingress
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
